### ISSUE TITLE
Karp urgent logging error

### ISSUE THREAD

**Issue by anne17** [spraakbanken/karp-backend-v5#15]
Det här händer ibland:

`Cannot print log file: 2018-09-17 12:55:31, Traceback (most recent call last):
  File "/export/htdocs_sbws/ws/karp/v4/backend.py", line 252, in handle_invalid_usage
    logging.debug('Error on url %s' % request.full_path)
  File "/export/htdocs_sbws/ws/karp/v4/venv/lib/python2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/export/htdocs_sbws/ws/karp/v4/venv/lib/python2.7/site-packages/werkzeug/utils.py", line 71, in __get__
    value = self.func(obj)
  File "/export/htdocs_sbws/ws/karp/v4/venv/lib/python2.7/site-packages/werkzeug/wrappers.py", line 546, in full_path
    return self.path + u'?' + to_unicode(self.query_string, self.url_charset)
  File "/export/htdocs_sbws/ws/karp/v4/venv/lib/python2.7/site-packages/werkzeug/_compat.py", line 202, in to_unicode
    return x.decode(charset, errors)
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 27: invalid continuation byte`

**Comment by kod-kristoff** [comment]
Issue moved to [spraakbanken/karp-backend-4 #4](https://github.com/spraakbanken/karp-backend-4/issues/4) via [**ZenHub**](https://www.zenhub.com/)
