### ISSUE TITLE
Apache 

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-backend-v5#5]
After rectifying the problems with Elasticsearch, I now run into problems with the webserver.
```bash
httpd -v
Server version: Apache/2.4.6 (CentOS)
Server built:   Oct 19 2017 20:39:16
```

I think it is a clash between my Apache .conf and Karp's .htaccess, but I'm not sure how the rewrite rules should be in the first place.

This is (the best of) what I get:
```bash
(venv) [centos@karp karp-backend]$ curl localhost/app
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://localhost/app/">here</a>.</p>
</body></html>
```
```bash
(venv) [centos@karp karp-backend]$ curl localhost/app/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /var/www/karp-backend/backend.wsgi/ was not found on this server.</p>
</body></html>
```
```bash
(venv) [centos@karp karp-backend]$ curl localhost/app/test
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /var/www/karp-backend/backend.wsgi/test was not found on this server.</p>
</body></html>
```

And this is my Apache `karp-backend.conf`:
```conf
    WSGIDaemonProcess local
    WSGIProcessGroup local

    Alias /app /var/www/karp-backend

    <Directory /var/www/karp-backend>
      Require all granted
      AllowOverride All
      Options +ExecCGI
      AddHandler wsgi-script .wsgi
    </Directory>
```
... and the .htaccess file you allready know.

I read `mod_wsgi`'s [Quick Configuration Guide](http://modwsgi.readthedocs.io/en/develop/user-guides/quick-configuration-guide.html) and they suggest to use the Apache directive `WSGIScriptAlias /app /var/www/karp-backend/backend.wsgi` in the .conf file. But that seems to break everything, with or without the .htaccess file.

**Comment by kristiank** [comment]
I went down the road to configure Apache as the mod_wsgi Quick Configuration Guide suggests. I got things working almost almost. I now get file permission errors:

```log
 mod_wsgi (pid=26206): Target WSGI script '/var/www/karp-backend/backend.wsgi' cannot be loaded as Python module.
 mod_wsgi (pid=26206): Exception occurred processing WSGI script '/var/www/karp-backend/backend.wsgi'.
 Traceback (most recent call last):
   File "/var/www/karp-backend/backend.wsgi", line 14, in <module>
     from src.main import app as real_application, load_urls
   File "/var/www/karp-backend/src/__init__.py", line 2, in <module>
     import server.log
   File "/var/www/karp-backend/src/server/log.py", line 19, in <module>
     with open(DEBUGFILE, "w") as f:
 IOError: [Errno 2] No such file or directory: u'log/20180328-debug.txt'
```

**Comment by kristiank** [comment]
As far as I can understand of the Traceback, the file path should be `/var/www/karp-backend/log/20180328-debug.txt`. I have created this file and even tried `chmod 777` on both the `log`-folder and the specified file.

Still I get the same error message as above (`IOError: [Errno 2] No such file or directory: u'log/20180328-debug.txt'`).

**Comment by kristiank** [comment]
I was able to "solve" this problem by:
1. re-commenting out the two lines for running the `activate_this.py`
1. and instead give the correct virtual environment path directly to mod_wsgi using the `python-path` option to the `WSGIDaemonProcess` directive
