### ISSUE TITLE
Stuck on IOError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by kristiank** [spraakbanken/karp-backend-v5#6]
Does anyone have any ideas to try?

* all files are chown to apache:apache
* the log/ folder is chmod to 777
* tried setting SELinux to permissive (with `setenforce 0`)

Here's my Apache error_log:
```log
[Mon Apr 02 14:23:49.922898 2018] [mpm_prefork:notice] [pid 29992] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Apr 02 14:23:51.146312 2018] [core:notice] [pid 30041] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Apr 02 14:23:51.147891 2018] [suexec:notice] [pid 30041] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Apr 02 14:23:51.275318 2018] [auth_digest:notice] [pid 30041] AH01757: generating secret for digest authentication ...
[Mon Apr 02 14:23:51.276465 2018] [lbmethod_heartbeat:notice] [pid 30041] AH02282: No slotmem from mod_heartmonitor
[Mon Apr 02 14:23:51.281282 2018] [mpm_prefork:notice] [pid 30041] AH00163: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5 configured -- resuming normal operations
[Mon Apr 02 14:23:51.281320 2018] [core:notice] [pid 30041] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Apr 02 14:24:24.212802 2018] [:error] [pid 30042] [remote 172.18.3.78:196] mod_wsgi (pid=30042): Target WSGI script '/var/www/karp-backend/backend.wsgi' cannot be loaded as Python module.
[Mon Apr 02 14:24:24.212885 2018] [:error] [pid 30042] [remote 172.18.3.78:196] mod_wsgi (pid=30042): Exception occurred processing WSGI script '/var/www/karp-backend/backend.wsgi'.
[Mon Apr 02 14:24:24.212925 2018] [:error] [pid 30042] [remote 172.18.3.78:196] Traceback (most recent call last):
[Mon Apr 02 14:24:24.212960 2018] [:error] [pid 30042] [remote 172.18.3.78:196]   File "/var/www/karp-backend/backend.wsgi", line 14, in <module>
[Mon Apr 02 14:24:24.213073 2018] [:error] [pid 30042] [remote 172.18.3.78:196]     from src.main import app as real_application, load_urls
[Mon Apr 02 14:24:24.213094 2018] [:error] [pid 30042] [remote 172.18.3.78:196]   File "/var/www/karp-backend/src/__init__.py", line 2, in <module>
[Mon Apr 02 14:24:24.213161 2018] [:error] [pid 30042] [remote 172.18.3.78:196]     import server.log
[Mon Apr 02 14:24:24.213185 2018] [:error] [pid 30042] [remote 172.18.3.78:196]   File "/var/www/karp-backend/src/server/log.py", line 19, in <module>
[Mon Apr 02 14:24:24.213263 2018] [:error] [pid 30042] [remote 172.18.3.78:196]     with open(DEBUGFILE, "w") as f:
[Mon Apr 02 14:24:24.213515 2018] [:error] [pid 30042] [remote 172.18.3.78:196] IOError: [Errno 2] No such file or directory: u'log/20180402-debug.txt'
```

**Comment by kristiank** [comment]
Do I need to specify `project_name = ''` in `backend.wsgi'?

**Comment by kristiank** [comment]
Do I need to better specify the paths in `config/config.json`? (the `.` doesn't seem to be a very absolute path)
```json
  "SETUP": {
    "ABSOLUTE_PATH" : ".",
    "SCRIPT_PATH" : ".",
```

**Comment by MalinAhlberg** [comment]
Yes, you should set the paths in `config/config.json` (unless you're using Docker). `backend.wsgi` should not need to be updated.

**Comment by kristiank** [comment]
Setting `"DEBUG_TO_STDERR":  true` in `config/config.json` let's me get around the problem for now. The backend is now running and I can run queries on it. I will keep this issue open until I can remedy the problem without debugging to stderr.

**Comment by MalinAhlberg** [comment]
In case SCRIPT_NAME is unclear (I guess it is, since it's not documented in Karp):
> SCRIPT_NAME
>The initial portion of the request URL's "path" that corresponds to the application object, so that the application knows its virtual "location". This may be an empty string, if the application corresponds to the "root" of the server.

(from https://www.python.org/dev/peps/pep-0333/)
